nname: main-workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Run a one-line script
        run: |
          echo running workflow in main branch
          hostname
          sleep 10
          touch /tmp/ymtomada
