name: CI
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Get the server name
        run: echo "Servername ${{ vars.server }}"
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Get the server name
        run: echo "Servername ${{ vars.server }}"
